### ISSUE TITLE
*** Error loading script: sd-TemporalKit-UI.py     Traceback (most recent call last):

### ISSUE THREAD

**Issue by maryannelizabethcooper** [CiaraStrawberry/TemporalKit#93]
Installing requirements for TemporalKit extension
Launching Web UI with arguments: --xformers --deepdanbooru --autolaunch --no-half-vae
*** Error loading script: sd-TemporalKit-UI.py
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\stable-diffusion-webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 23, in <module>
        from modules.ui import create_toprow, create_sampler_and_steps_selection
    ImportError: cannot import name 'create_toprow' from 'modules.ui' (C:\stable-diffusion-webui\modules\ui.py)

I used temporalkit really well, but last night suddenly stoppped.... and then I restarted SD webUI but I got this message...
Please Please help me.....

**Comment by UriahKong** [comment]
这是更新了1.60版本后好多插件都用不了,要等作者修复就行

**Comment by CrisisBomberman** [comment]
I'm having the same issue, it just needs to be updated for latest automatic 1111

**Comment by scooller** [comment]
Same here version: [v1.6.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4)  •  python: 3.10.11  •  torch: 2.0.1+cu118  •  xformers: 0.0.20

**Comment by naduarte2** [comment]
same error here after updating from SD v1.5.2 to 1.6.0.
 
*** Error loading script: sd-TemporalKit-UI.py
    Traceback (most recent call last):
      File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 23, in <module>
        from modules.ui import create_toprow, create_sampler_and_steps_selection
    ImportError: cannot import name 'create_toprow' from 'modules.ui' (D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\ui.py)

My solution was to install a second SD with symlinks and then having 2 WebUI, 1 updated to v1.6.0 without TemporalKit and 1 outdated with v1.5.2 with TemporalKit. If you want to do the same the steps I did were:

1. Download and extract https://github.com/AUTOMATIC1111/stable-diffusion-webui/archive/refs/tags/v1.5.2.zip

2. Edit webui-user.bat with the next paths (not venv in case it update unwanted things) and Run it.
```python
set PYTHON=D:\Python\Python3.10.6150.1013\python.exe
set GIT=C:\Program Files\Git\cmd\git.exe
set VENV_DIR=
set COMMANDLINE_ARGS=--autolaunch --xformers --lowvram --opt-sdp-no-mem-attention --opt-split-attention --no-half-vae --theme dark
``` 

3. Close completely the WebUI and CMD. 
4. Delete folders of SD v1.5.2: ".\embeddings\" , ".\models\" and "\.outputs\"
5. Open CMD as Administrator and create the symlinks to the SD v1.6.0 that contains all the embeddings, models and outputs (to not copy/paste or re-download) with:
```python
mklink /D "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui-1.5.2\embeddings" "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\embeddings" 
mklink /D "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui-1.5.2\models" "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\models" 
mklink /D "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui-1.5.2\outputs" "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\outputs" 
``` 
6. Done. You have both SD WebUI version working. 
7. You can delete the SDv1.5.2 folder when TemporalKit is fixed to work with v1.6.0.

**Comment by Criswa7** [comment]
Certainly, here is the translation of your text into English:

I had the same issue with File "C:\Users\crist\AppData\Local\Programs\Python\Python311\Lib\importlib_init_.py", line 126, in import_module
return _bootstrap.gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\crist\Documents\GEN_IMG\stable-diffusion-webui\venv\Lib\site-packages\huggingface_hub\hf_api.py", line 35, in <module>
from huggingface_hub.utils import (
File "C:\Users\crist\Documents\GEN_IMG\stable-diffusion-webui\venv\Lib\site-packages\huggingface_hub\utils_init.py", line 18, in <module>
from . import tqdm as _tqdm # _tqdm is the module
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\crist\Documents\GEN_IMG\stable-diffusion-webui\venv\Lib\site-packages\huggingface_hub\utils\tqdm.py", line 63, in <module>
from tqdm.auto import tqdm as old_tqdm
ModuleNotFoundError: No module named 'tqdm.auto'
What I did was delete TemporalKit from the extensions folder and then I deleted the venv folder (it's the virtual environment). Then I ran webui-user again to reinstall everything necessary and now it works.

**Comment by Alan-Cao-ShengJin** [comment]
change create_toprow by Toprow in line 23 of extensions\TemporalKit\scripts\sd-TemporalKit-UI.py

`from modules.ui import create_toprow, create_sampler_and_steps_selection`
to
`from modules.ui import Toprow, create_sampler_and_steps_selection`


and then copy this function in modules/ui.py

```
def create_sampler_and_steps_selection(choices, tabname):
    return scripts.scripts_txt2img.script('Sampler').steps, scripts.scripts_txt2img.script('Sampler').sampler_name
```

**Comment by lavibeats** [comment]
I have done what was written here but still not working:

*** Error loading script: sd-TemporalKit-UI.py
    Traceback (most recent call last):
      File "F:\STABLE-DIFFUSION-COMFYUI\webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\STABLE-DIFFUSION-COMFYUI\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\STABLE-DIFFUSION-COMFYUI\webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 23, in <module>        from modules.ui import Toprow, create_sampler_and_steps_selection
    ImportError: cannot import name 'Toprow' from 'modules.ui' (F:\STABLE-DIFFUSION-COMFYUI\webui\modules\ui.py)


version: [v1.9.3]  •  python: 3.10.11  •  torch: 2.1.2+cu121  •  xformers: N/A  •  gradio: 3.41.2  •  checkpoint: [ea1b665634]
